# GitHub Action with Dependency Caching
name: CI with Caching

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-with-cache"
  build-with-cache:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Cache pip dependencies using the specific cache key
      - name: Cache pip dependencies
        uses: actions/cache@v4
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: cache-20e9ca5

      # The required step with specific name for cache priming verification
      - name: prime-cache-20e9ca5
        run: |
          echo "=== Cache Priming Step ==="
          echo "Email: 23f3003784@ds.study.iitm.ac.in"
          echo "Cache key: cache-20e9ca5"
          echo "Cache hit status: ${{ steps.cache-pip.outputs.cache-hit }}"
          if [[ "${{ steps.cache-pip.outputs.cache-hit }}" == "true" ]]; then
            echo "✅ Cache hit! Dependencies were restored from cache."
          else
            echo "❌ Cache miss. Dependencies will be installed and cache will be saved."
          fi
          echo "Cache priming step completed successfully!"
          echo "Step status: SUCCESS"

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Verify installation
      - name: Verify installation
        run: |
          echo "Verifying installed packages..."
          pip list
          echo "Installation verification completed!"

      # Test cached dependencies
      - name: Test cached dependencies
        run: |
          python -c "import pandas; import numpy; import fastapi; print('All dependencies imported successfully!')"